name: AvatarMC
version: '${project.version}'
main: sprucegoose.avatarmc.AvatarMC
api-version: 1.19
depend: [WorldGuard, Factions, PvPManager]
commands:
  test:
    description: Test Command for AvatarMC plugin.
    usage: /<command>
  skills:
    description: Open the skills menu
    usage: /<command>
    aliases:
      test2
  give_ability:
    description: teaches player ability
    usage: /<command> ability_name
  give_ability_book:
    description: gives player ability book
    usage: /<command> player_name ability_name source
  mob_use_hostile_ability:
    description: uses a hostile ability as a mob
    usage: /<command> casterID target_player ability
  remove_ability:
    description: removes ability from player
    usage: /<command> ability_name
  set_bender:
    description: sets bending type for player
    usage: /<command> [player_name] ability_name
  remove_bender:
    description: Removes bending from player
    usage: /<command> [player_name]
  test3:
    description: Test 3 Command for AvatarMC plugin.
    usage: /<command>
  test4:
    description: Test 4 Command for AvatarMC plugin.
    usage: /<command>